### ISSUE TITLE
More info on pypi would be nice

### ISSUE THREAD

**Issue by churnikov** [stsouko/marvin_dash#2]
Page on PyPI really lacks info on how to use your module
https://pypi.org/project/dash_marvinjs/

Secondly, I don't quite understand, how to use your module from this section https://github.com/stsouko/marvin_dash#install-from-pypi
Could you give a bit more detail there?

**Comment by stsouko** [comment]
see updated readme.
feel free in case of any new questions.

**Comment by churnikov** [comment]
Hey!

I was able to start `usage.py` script and got `No valid license found error`

![image](https://user-images.githubusercontent.com/8545082/121913033-b9dc8900-cd39-11eb-9f8c-0757600d59d4.png)

I'm trying to follow ChemAxon guide on license setup, but I don't get, where should I put license file? My tree structure looks like this:

```
├── assets
│   └── mjs
│       ├── editor.html
│       ├── editorws.html
│       ├── gui
│       │   └── ...
│       ├── js
│       │   └── ...
├── license.cxl
├── usage.py
└── web.config
```

**Comment by churnikov** [comment]
Okay, I figured that out via this tutorial
https://youtu.be/Zqf6fAZhyZ8?t=617

**Comment by churnikov** [comment]
I have another question, but I'll ask it in another issue 😸
